### ISSUE TITLE
nothing named gis:project-lat-lon defined error

### ISSUE THREAD

**Issue by koushiksura** [NetLogo/GIS-Extension#29]
I am trying to use project-lat-lon primitive but I am getting an error. Isn't it released yet? If not, when are you planning to roll out this primitive? @JamesHovet 

Thanks in advance...

**Comment by JamesHovet** [comment]
@koushiksura Glad to see there's some demand for the new feature already. We went ahead and updated the extension in the main NetLogo extensions manager. You should be able to open it up (Tools > Extensions in the NetLogo app), find the GIS extension, and update to the latest version. After that the project-lat-lon primitive should work. Lemme know if you run into any other issues.
