### ISSUE TITLE
NetLogo 6.2 Parsing error while loading .asc file

### ISSUE THREAD

**Issue by dpriss** [NetLogo/GIS-Extension#38]
Hello,
I'm trying to set up my NetLogo world with a raster (.asc) and a shapefile (.shp). The shapefile seems to work fine but when I try to load the raster I get a parsing error:

Extension exception: error parsing number
error while observer running GIS:LOAD-DATASET
  called by procedure SETUP
  called by Button 'setup'

org.nlogo.nvm.WrappedExtensionException: Extension exception: error parsing number
 at org.nlogo.prim._externreport.report(_externreport.java:35)
 at org.nlogo.prim._asm_proceduresetup_setobservervariable_1.perform()
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: org.nlogo.api.ExtensionException: error parsing number
 at org.myworldgis.io.asciigrid.AsciiGridFileReader.<init>(AsciiGridFileReader.java:105)
 at org.myworldgis.netlogo.LoadDataset.loadAsciiGrid(LoadDataset.java:135)
 at org.myworldgis.netlogo.LoadDataset.reportInternal(LoadDataset.java:193)
 at org.myworldgis.netlogo.GISExtension$Reporter.report(GISExtension.java:38)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 ... 9 more

NetLogo 6.2.0
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.12
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: setup_gis_abm

10:24:14.602 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:24:14.602 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
10:24:14.602 OutputEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:24:14.602 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
10:24:14.602 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
10:24:14.602 OutputEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:24:14.595 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:24:14.595 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:24:14.517 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:24:14.395 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

As I'm rather new to NetLogo and programming, I don't really understand what is going wrong and I couldn't find a solution on online forums. I assume it's just something simple. I also tried to attach the .asc file as txt, but this didn't seem to work. Therefore, here are the first few lines of the file:

ncols         9366
nrows         5141
xllcorner     31,272916666667
yllcorner     36,867361109969
cellsize      0,000277777778
NODATA_value  -9999
1586 1591 1597 1599 1598 1596 1591 1588 1587 1582 1576 1569 1561 1554 1546 1541 1540 1543 1546 1551 1556 1567 1583 1598 1611 1623 1633 1643 1651 1657 1661 1665 1667 1672 1677 1684 1691 1698 1705 1712 1719 1733 1741 1749 1758 1768 1776 1779 1780 1777 1774 1775 1775 1779 1783 1789 1796 1804 1814 1829 1841 1851 1860 1868 1877 1886 1888 1891 1895 1898 1899 1902 1907 1908 1908 1908 1906 1905 1906 1905 1908 1911 1916 1922 1929 1938 1948 1957 1965 1973 1979 1985 1990 1993 1989 1982 1974 1967 1958 1949 1940 1931 1922 1915 1911 1910 1910 1914 1918 1923 1930 1937 1943 1954 1963 1972 1980 1988 2001 2013 2024 2031 2039 2047 2055 2065 2074 2081 2089 2097 2104 2109 2111 2114 2113 2111 2110 2110 2110 2110 2109 2107 2102 2097 2090 2082 2071 2063 2052 2039 2026 2015 2008 2001 1994 1987 1984 1982 1983 1981 1977 1974 1976 1975 1970 1963 1957 1949 1939 1935 1937 1944 1952 1963 1972 1978 1981 1978 1972 1965 1959 1954 1949 1947 1946 1944 1940 1936 1930 1923 1915 1909 1903 1895 1888 1879 1870 1863 1852 1844 1837 1831 1825 1820 1816 1808 1804 1802 1804 1806 181

Many thanks,
Deborah

**Comment by LaCuneta** [comment]
Hey @dpriss, since you closed this I'm assuming you resolved your issue?  If you did and you have time, please feel free to add a comment describing the solution you came to, as that might help others who run into the same problem in the future.  Thanks!

**Comment by dpriss** [comment]
Hi, 
sorry, I meant to post an update as I found the solution myself and it was quiet simple. I just had to change the decimals in the header, NetLogo obviously doesn't like commas. So, instead of 

xllcorner 31,272916666667
yllcorner 36,867361109969
cellsize 0,000277777778

I now have 

xllcorner 31.272916666667
yllcorner 36.867361109969
cellsize 0.000277777778

which works perfectly fine.

**Comment by LaCuneta** [comment]
That's great to know, thank you for the update!
