### ISSUE TITLE
netlogo 6.3 R error

### ISSUE THREAD

**Issue by kidstoneszk** [NetLogo/GIS-Extension#41]
![image](https://user-images.githubusercontent.com/16143841/194739022-d699a0e8-94de-4459-ba8d-21b41039a9c9.png)
when i have installed netlogo 6.3，and open example1 in R example there are a error appear, please help me

**Comment by LaCuneta** [comment]
Misfile of [this issuein the R-Extension repo](https://github.com/NetLogo/R-Extension/issues/27).
