### ISSUE TITLE
gis:find-features always returns partial string matches, StringUtils.matches problem

### ISSUE THREAD

**Issue by thomaspurk** [NetLogo/GIS-Extension#48]
Note: I know enough to review the source code and track down the possible issue. But I am not setup to code, build, and test any changes. So that is why I am not submitting a Pull Request. I would really appreciate anyone who can address this issue.
 
NetLogo 6.3.0- Windows 11 64 bit
GIS Extension - bundled with 6.3.0

- I have loaded a roads ShapeFile as "texas-roads-dataset"
- Attribute data contains column "FULLNAME" with values such as "I- 35A Bus" "I-35 N" and "I- 35"
- I want to create a List of features where "FULLNAME" exactly equals "I- 35"

Problem: my code below creates a feature  List that includes "I- 35" but also "I- 35A Bus" and "I-35 N"

`let i35-roads gis:find-features texas-roads-dataset "FULLNAME" "I- 35"`

I believe the issue is in the matches function of StringUtils.WildvardMatcher class. Lines 32-44 of the current StringUtils.java file.

```
        public boolean matches (String str) {
            int lastIndex = 0;
            for (int i = 0; i < _subpatterns.length; i += 1) {
                int index = str.indexOf(_subpatterns[i], lastIndex);
                if (index < lastIndex) {
                    return false;
                } else {
                    lastIndex = index + _subpatterns[i].length();
                }
            }
            return true;
        }
```

In this example _subpatterns would be set to a single value array ["I- 35"] due to the class instantiation call from line 91 of VectorDataSearch.java

`StringUtils.WildcardMatcher matcher = new StringUtils.WildcardMatcher(args[2].getString());`

Example: the str input parameter to the matches function noted above is "I- 35A Bus"

This should NOT match but it does.

Because _subpatterns is a single member array, the for loop on _subpatterns will iterate only once.

The str.indexOf line will return 0, because the match pattern "I- 35" is found at index 0 of "I- 35A Bus"

And since index = 0 and lastIndex = 0, the if statement will NOT return false, the loop will terminate after 1 iteration allowing the function to terminate on the "return true;" call.

In effect, the matches function will behave as a "contains" operation rather than an exact match operation.

**Comment by LaCuneta** [comment]
Thank you so much for your detailed bug report!  

I have a fix for this done.  It's failing our automated tests due to an unrelated dependency issue.  Once I've got that resolved, I'll merge the fix, close this issue, and do a quick fix to the extensions manger.

**Comment by LaCuneta** [comment]
@thomaspurk This is now released on the extensions manager; it requires NetLogo 6.3.0 due to Java version updates.
