### ISSUE TITLE
NetLogo GIS Extension Problem

### ISSUE THREAD

**Issue by gmavrom** [NetLogo/GIS-Extension#9]
Hello,

I am trying to create an applet to incorporate in my blog. The model utilises the GIS extension and I seem to have a few issues. I believe that this is not my problem because I have the exactly same problem as when I run this:

http://ccl.northwestern.edu/netlogo/5.0.3/applet/gis.html

The error I get is:

Extension exception: points must form a closed linestring
error while observer running GIS:LOAD-DATASET
  called by procedure SETUP
  called by Button 'setup'

Anyone have any idea why this is occuring? Any help is appreciated! 

Thanks a lot,

George

**Comment by SethTisue** [comment]
almost certainly a duplicate of #2
